vals = [['Branch 0', 'Varanasi', 'Asset 31'],
['Branch 1', 'Indore', 'Asset 48'],
['Branch 2', 'Ghaziabad', 'Asset 38'],
['Branch 3', 'Surat', 'Asset 71'],
['Branch 4', 'Bengaluru', 'Asset 8'],
['Branch 5', 'Ghaziabad', 'Asset 79'],
['Branch 6', 'Bhopal', 'Asset 3'],
['Branch 7', 'Srinagar', 'Asset 37'],
['Branch 8', 'Varanasi', 'Asset 20'],
['Branch 9', 'Srinagar', 'Asset 70'],
['Branch 10', 'Surat', 'Asset 80'],
['Branch 11', 'Mumbai', 'Asset 6'],
['Branch 12', 'Nagpur', 'Asset 74'],
['Branch 13', 'Pune', 'Asset 26'],
['Branch 14', 'Bhopal', 'Asset 98'],
['Branch 15', 'Kalyan', 'Asset 93'],
['Branch 16', 'Aurangabad', 'Asset 72'],
['Branch 17', 'Madurai', 'Asset 86'],
['Branch 18', 'Thana', 'Asset 73'],
['Branch 19', 'Delhi', 'Asset 87'],
['Branch 20', 'Kalyan', 'Asset 84'],
['Branch 21', 'Kalyan', 'Asset 12'],
['Branch 22', 'Visakhapatnam', 'Asset 40'],
['Branch 23', 'Srinagar', 'Asset 14'],
['Branch 24', 'Srinagar', 'Asset 89'],
['Branch 25', 'Hyderabad', 'Asset 90'],
['Branch 26', 'Pune', 'Asset 63'],
['Branch 27', 'Meerut', 'Asset 5'],
['Branch 28', 'Agra', 'Asset 100'],
['Branch 29', 'Surat', 'Asset 32'],
['Branch 30', 'Navi Mumbai', 'Asset 77'],
['Branch 31', 'Indore', 'Asset 14'],
['Branch 32', 'Nashik', 'Asset 5'],
['Branch 33', 'Surat', 'Asset 61'],
['Branch 34', 'Ludhiana', 'Asset 10'],
['Branch 35', 'Aurangabad', 'Asset 63'],
['Branch 36', 'Faridabad', 'Asset 59'],
['Branch 37', 'Srinagar', 'Asset 99'],
['Branch 38', 'Dhuri', 'Asset 19'],
['Branch 39', 'Bengaluru', 'Asset 74'],
['Branch 40', 'Patna', 'Asset 64'],
['Branch 41', 'Chennai', 'Asset 86'],
['Branch 42', 'Srinagar', 'Asset 58'],
['Branch 43', 'Lucknow', 'Asset 38'],
['Branch 44', 'Aurangabad', 'Asset 12'],
['Branch 45', 'Allahabad', 'Asset 1'],
['Branch 46', 'Patna', 'Asset 6'],
['Branch 47', 'Indore', 'Asset 58'],
['Branch 48', 'Allahabad', 'Asset 44'],
['Branch 49', 'Varanasi', 'Asset 2']]
import random
for i in vals:
    i[2] = random.randint(0,5000000)
    print(f"INSERT INTO branch VALUES {tuple(i)};")